### ISSUE TITLE
multiple result values in 1 request

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [oraclize/ethereum-examples#10]
hey, how to return more then 1 result from the request ?

**Comment by D-Nice** [comment]
Oraclize provides parsing helpers which may help you get what you desire. Specifically with a JSON result, you could use our JSONPath helper: https://docs.oraclize.it/#general-concepts-parsing-helpers

There's also a link to the JSONPath standards in there, to get a better understanding of the possibilities.

Even with that, the best you can likely do is get a trimmed down JSON, or at least an array back. But at least it's trimmed, and any on-chain parsing should, to read and use those multiple results, will be more cheaper.
