### ISSUE TITLE
Not getting Youtube views when using in private network with Ethereum-bridge

### ISSUE THREAD

**Issue by sivachaitanya** [oraclize/ethereum-examples#14]
I have a 2 node private cluster running inside a docker container, I have used Ethereum bridge to deploy the connector contracts successfully on the network and following is the log from it - 

bash-4.3# node bridge -a 9
Please wait...
[2017-12-20T05:59:56.273Z] INFO you are running ethereum-bridge - version: 0.5.5
[2017-12-20T05:59:56.281Z] INFO saving logs to: ./bridge.log
[2017-12-20T05:59:56.283Z] INFO using active mode
[2017-12-20T05:59:56.283Z] INFO Connecting to eth node http://localhost:8545
[2017-12-20T06:00:00.326Z] INFO connected to node type Geth/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9.2
[2017-12-20T06:00:03.251Z] WARN Using 0xb1d3073bcc45462a3b0dfe69902cdd12971efec9 to query contracts on your blockchain, make sure it is unlocked and do not use the same address to deploy your contracts
[2017-12-20T06:00:03.797Z] INFO deploying the oraclize connector contract...
[2017-12-20T06:00:15.515Z] INFO connector deployed to: 0x41b0811e70d135540b0589bc578922995adb167d
[2017-12-20T06:00:16.105Z] INFO deploying the address resolver with a deterministic address...
[2017-12-20T06:00:53.519Z] INFO address resolver (OAR) deployed to: 0x6f485c8bf6fc43ea212e93bbf8ce046c7f1cb475
[2017-12-20T06:00:53.523Z] INFO updating connector pricing...
[2017-12-20T06:01:11.435Z] INFO successfully deployed all contracts
[2017-12-20T06:01:11.483Z] INFO instance configuration file saved to /root/oracle/ethereum-bridge/config/instance/oracle_instance_20171220T060111.json
[2017-12-20T06:01:11.486Z] INFO you are using a deterministic OAR, you don't need to update your contract
[2017-12-20T06:01:12.376Z] INFO Listening @ 0x41b0811e70d135540b0589bc578922995adb167d (Oraclize Connector)

I have modified the Youtube views code for the constructor to include the OAR as specified in the documentation and here is the code for it - 

```
pragma solidity ^0.4.0;
import "github.com/oraclize/ethereum-api/oraclizeAPI.sol";
contract YoutubeViews is usingOraclize {

    uint public viewsCount;

    function YoutubeViews() {
        OAR = OraclizeAddrResolverI(0x6f485c8bf6fc43ea212e93bbf8ce046c7f1cb475);      //add this line once using Oraclize in private chain environment
        update(0);
    }

    function __callback(bytes32 myid, string result) {
        if (msg.sender != oraclize_cbAddress()) throw;
        viewsCount = parseInt(result, 0);
        // do something with viewsCount
        // (like tipping the author once viewsCount > X?)
        update(60*10); // update viewsCount every 10 minutes
    }

    function update(uint delay) {
        oraclize_query(delay, 'URL', 'html(https://www.youtube.com/watch?v=9bZkp7q19f0).xpath(//*[contains(@class, "watch-view-count")]/text())');
    }

}
```

I am using Remix to deploy the contracts to my private network and everything went well, until I query the public viewscount value it always gives me 0. Not sure what going wrong here ?

**Comment by D-Nice** [comment]
There's a number of issues straight off the bat you will encounter.

First, XPath is not exactly considered reliable, as you can see, the example above is dependent upon an HTML class. 

Second, since the Oraclize fetching server is now based out of Europe (might've been US before?), the result actually comes in the form of `3.022.531.913 Aufrufe` using period separation rather than comma separation which breaks the current parseInt helper. 

However, you should not be getting zero. I have tested it myself, and am getting a result of 3, which is due to the above issue, and can be rectified with a custom parser (could re-use the existing one, and replace the `.` ascii code of 46 with that for a comma `,` which Europeans use, for decimal separation, which I think is 44). 

Can you provide the query ids emitted from the bridge, when you query the contract? Remember it's an asynchrnous process, so it takes time for the viewsCount variable to get updated.

**Comment by sivachaitanya** [comment]
Thanks @D-Nice  I got the thing solved now, why I am getting zero because for some reason my bridge is paused or stopped. I redeployed the contracts, got a new OAR and made sure the bridge is receiving events. Then when I fired event from smart contracts in remix I am able to see the queries passed in the ethereum bridge and almost instantaneously generating results in my private blockchain. And you are right about 3.022.531.913 Aufrufe thing, was very weird. What would be the error I will be getting if the bridge is unable to send queries to the Oraclize service ?

**Comment by D-Nice** [comment]
It would likely be a generic HTTP error if queries to Oraclize are failing to be sent.

**Comment by D-Nice** [comment]
Here's the example with a working parseInt

```
/*
   Youtube video views

   This contract keeps in storage a views counter
   for a given Youtube video.
*/


pragma solidity ^0.4.0;
import "github.com/oraclize/ethereum-api/oraclizeAPI.sol";

contract YoutubeViews is usingOraclize {
    
    uint256 public viewsCount;
    
    event newOraclizeQuery(string description);

    function YoutubeViews() {
        update();
    }
    
    function __callback(bytes32 myid, string result) {
        if (msg.sender != oraclize_cbAddress()) throw;
        viewsCount = parseIntEuro(result, 0);

        // do something with viewsCount. like tipping the author if viewsCount > X?
    }
    
    function update() payable {
        newOraclizeQuery("Oraclize query was sent, standing by for the answer..");
        oraclize_query('URL', 'html(https://www.youtube.com/watch?v=9bZkp7q19f0).xpath(//*[contains(@class, "watch-view-count")]/text())');
    }
    
    function parseIntEuro(string _a, uint _b) internal pure returns (uint) {
        bytes memory bresult = bytes(_a);
        uint mint = 0;
        bool decimals = false;
        for (uint i=0; i<bresult.length; i++){
            if ((bresult[i] >= 48)&&(bresult[i] <= 57)){
                if (decimals){
                   if (_b == 0) break;
                    else _b--;
                }
                mint *= 10;
                mint += uint(bresult[i]) - 48;
            } else if (bresult[i] == 44) decimals = true;
        }
        if (_b > 0) mint *= 10**_b;
            return mint;
    }
    
} 
          
``

**Comment by IamChuancey** [comment]
Do your private network build by geth? @ @sivachaitanya
