### ISSUE TITLE
Takes more than 30 minutes for query to be performed

### ISSUE THREAD

**Issue by ftppro** [oraclize/ethereum-examples#15]
I created the following contract to test your 'oraclize' functionaity:
https://ropsten.etherscan.io/address/0xdbe01bab0eecb80ec70f249825e775debd03c75b

I modified your 'KrakenPriceTicker', to have only one query performed immediately.

The etherscan report indicates that it took 37 minutes for your query to be performed (from 0xdc8f20170c0946accf9627b3eb1513cfd1c0499f).

-----------------------------------------------------------

The following contract requested a query to be performed today at 11:00am cst:
https://ropsten.etherscan.io/address/0x29b0d219e49f171a0434db9893a696939dfc0774

Here is the line of code that made that request:
oraclize_query(1516035600, "URL", "json(http://api.wunderground.com/api/51a133905ecec55c/conditions/q/37075.json).current_observation.temp_f");

It is now 12:00 noon cst, and the query has not been performed.

**Comment by Gim6626** [comment]
Similar trouble on Rinkeby - 7 hours between request and response.

**Comment by D-Nice** [comment]
There may have been some high volume or bridge issues during this time. We have some improvements that have been made since, and watchdogs checking the tesnets for QoS.
