### ISSUE TITLE
Recursive Queries Fail when using the Web IDE

### ISSUE THREAD

**Issue by postables** [oraclize/ethereum-examples#16]
I'm using the slightly modified Diesel USD Price Example to conduct a recursive query.
Everything works when not using a recursive query, however the moment i introduce a recursive query, all calls fail with an invalid opcode.

Here's my source code 

https://gist.github.com/postables/3a8e5de07028a470f52a8a569c26e74a

**Comment by bertani** [comment]
Do you have enough balance in your contract to cover for the query cost? The first query is free, but all the subsequent calls come at a cost.
