### ISSUE TITLE
"Random datasource is currently available on the Ethereum mainnet"

### ISSUE THREAD

**Issue by BrunoAl25** [oraclize/ethereum-examples#24]
I can´t find this on mainnet

Can you send me the link of the contract?

Thanks

**Comment by D-Nice** [comment]
> Note: the random datasource is currently available on the Ethereum mainnet and on all Ethereum public testnets only"

The note is meant to imply that the random datasource service is only available to use in the aforementioned contexts, not that there's a specific contract.
