### ISSUE TITLE
Kraken Price Example - Callback never fires

### ISSUE THREAD

**Issue by jacobscarter** [oraclize/ethereum-examples#3]
When deploying the example as is, the newKrakenPriceTicker Event never fires.

**Comment by bertani** [comment]
Hello, could you please provide more details? The example code should be working fine. On which context are you testing this? Can you share the deployed contract address for public inspection? Thanks!

**Comment by sahilsarpal15** [comment]
called only once in my case

**Comment by sahilsarpal15** [comment]
any solution for that ?

**Comment by bertani** [comment]
If you don't send along / the contract doesn't hold any ether, that code is supposed to run only one time as calling oraclize_query needs a fee to be paid. The first query comes at no cost, this is why you are getting it called auccessfully one time only. Check out our pricing section at docs.oraclize.it to know more about this!

**Comment by marcogiglio** [comment]
I will close due to inactivity. Please, continue here if the problem persists and I will reopen the issue.
