### ISSUE TITLE
Update Truffle examples READMEs

### ISSUE THREAD

**Issue by gskapka** [oraclize/ethereum-examples#42]
...to reflect the new stable release of Truffle 5. 

***

### Possible better way to achieve above:

Have Truffle 5 in the `package.json` & recommend running Truffle via `npx` after an `npm install`.

:heavy_plus_sign: __Pros__ :
- We don't have to overwrite user's globally installed versions of Truffle (if they have any).
- We can now control & pin the Truffle version used via `package.json`.

:heavy_minus_sign: __Cons__: 
- Fewer people know about `npx` magic.
- Truffle docs themselves recommend the global install.

**Comment by D-Nice** [comment]
Teaching people to use npx is probably a good thing rather than a bad one I'd say. So I'm all for this.

**Comment by riccardopersiani** [comment]
New READMEs updated with `npx` magic and much more in PR #48 by @gskapka.
