### ISSUE TITLE
Solidity examples README proof-type mixup.

### ISSUE THREAD

**Issue by gskapka** [oraclize/ethereum-examples#43]
This line in the Ethereum Examples solidity dir's `README.md`...

> Requesting TLSNotary authenticity proofs! #1

... links via the `#1` to the kraken example, which uses an _Android_ proof, not TLSN!

**Comment by D-Nice** [comment]
PR this change at next README update please.

**Comment by D-Nice** [comment]
@gskapka any updates on this?

**Comment by gskapka** [comment]
Oops - accidentally let this one slide since I wasn't assigned to it. I've assigned myself, done it, and now __[PRd it here](https://github.com/oraclize/ethereum-examples/pull/53)__.

**Comment by gskapka** [comment]
Closing ∵ merged.
