### ISSUE TITLE
how do you get the oracalize api key? 

### ISSUE THREAD

**Issue by tommy2049** [oraclize/ethereum-examples#6]

**Comment by D-Nice** [comment]
Which API key are you inquiring about? Oraclize itself has no API keys yet for its services. If you're asking about testing Oraclize's query service, you can try it here right in your browser before any smart contract development: http://app.oraclize.it/home/test_query

Please clarify if you're looking for something else.

**Comment by tommy2049** [comment]
I was reading some contracts online, and this was one of the queries to oracalize 


        bytes32 rngId = oraclize_query("nested", "[URL] ['json(https://api.random.org/json-rpc/1/invoke).result.random[\"serialNumber\",\"data\"]', '\\n{\"jsonrpc\":\"2.0\",\"method\":\"generateSignedIntegers\",\"params\":{\"apiKey\":${[decrypt] BLTr+ZtMOLP2SQVXx8GRscYuXv+3wY5zdFgrQZNMMY3oO/6C7OoQkgu3KgfBuiJWW1S3U/+ya10XFGHv2P7MB7VYwFIZd3VOMI/Os8o1uJCdGGZgpR0Dkm5QoNH7MbDM0wa2RewBqlVLFGoZX1PJC+igBPNoHC4=},\"n\":1,\"min\":1,\"max\":100,\"replacement\":true,\"base\":10${[identity] \"}\"},\"id\":1${[identity] \"}\"}']", gasForOraclize);

**Comment by D-Nice** [comment]
Oraclize acts as a data carrier service. You don't need API keys for us, but for the web API service you wish to interact with. In the case of the above query, you need an API key from https://www.random.org/

**Comment by D-Nice** [comment]
For security, the random.org API key there is encrypted, which gets decrypted once it reaches us so we can do the query.

You can read up on how to encrypt certain parts on the following documentation: https://docs.oraclize.it/#ethereum-advanced-topics-encrypted-queries

**Comment by tommy2049** [comment]
oh, i need to read better next time, thanks for clarifying!
