### ISSUE TITLE
Oraclize not returning data when using example contract

### ISSUE THREAD

**Issue by wanshun123** [oraclize/ethereum-examples#7]
I am trying to use the example Oraclize contracts, including KrakenPriceTicker.sol. Here's my contract (modified very slightly - including pointing it to oraclizeAPI_0.4.sol, since oraclizeAPI.sol as the contract in the repository tries to import is a blank contract now):

```
pragma solidity ^0.4.0;
import "github.com/oraclize/ethereum-api/oraclizeAPI_0.4.sol";

contract KrakenPriceTicker is usingOraclize {

    string public ETHXBT;
    uint public timesCalled;
    uint public timesFailed;

    event newOraclizeQuery(string description);
    event newKrakenPriceTicker(string price);


    function KrakenPriceTicker() payable {
        oraclize_setProof(proofType_TLSNotary | proofStorage_IPFS);
    }

    function __callback(bytes32 myid, string result, bytes proof) {
        ETHXBT = result;
        newKrakenPriceTicker(ETHXBT);
        update();
    }

    function update() payable {
        if (oraclize_getPrice("URL") > this.balance) {
            newOraclizeQuery("Oraclize query was NOT sent, please add some ETH to cover for the query fee");
            timesFailed++;
        } else {
            newOraclizeQuery("Oraclize query was sent, standing by for the answer..");
            oraclize_query(60, "URL", "json(https://api.kraken.com/0/public/Ticker?pair=ETHXBT).result.XETHXXBT.c.0");
            timesCalled++;
        }
    }

}
```
When the `update()` function is called and some ether and gas sent with it, it should call the kraken.com api and update the value of `ETHXBT` with what's returned. However, the value of `ETHXBT` is always blank. I know the oraclize_query is being called, or at least it passes that line, because the `timesCalled` variable does increment. Going directly to https://api.kraken.com/0/public/Ticker?pair=ETHXBT shows there shouldn't be any problem.

I've deployed the above contract at https://ropsten.etherscan.io/address/0x2c51daecf702f2afe3abee2cc84570ee17f75650 (I've tried to call update() several times, including by sending 0.1 ether).

**Comment by D-Nice** [comment]
Apologies, there seems to have been an outage with our architecture on the Ropsten test network. It should be fixed within the hour, and the missed queries should come in. We are working on some fixes to increase the reliability of the testnets.

In the meantime, you can also test in our local sandbox using http://dapps.oraclize.it/browser-solidity/ which is probably better for prototyping and more reliable.

**Comment by sumitpatel93** [comment]
http://dapps.oraclize.it/browser-solidity/  This aint working too

**Comment by gskapka** [comment]
@sumitpatel93 The fork of remix we maintained back then has since been deprecated. You can find our plugin under the plugins tab (bottom of the right hand panel) at the __[official Remix site here.](https://remix.ethereum.org)__
