### ISSUE TITLE
Random example does not works on Rinkeby and Ropsten

### ISSUE THREAD

**Issue by nosuchip** [oraclize/ethereum-examples#9]
I am trying to get worked this [contract](https://github.com/oraclize/ethereum-examples/blob/master/solidity/random-datasource/randomExample.sol). It was deployed [here](https://rinkeby.etherscan.io/address/0xc8c460937e9aa6231913a56a033e0527a338c2b8) and as you can see in "Event Logs" section of the transaction [0x89646db5402eaa5d4bd9dc97acbb8953154d236a9111ce18c7e59cc2d9035469](https://rinkeby.etherscan.io/tx/0x89646db5402eaa5d4bd9dc97acbb8953154d236a9111ce18c7e59cc2d9035469) contains only strange event indicated that oraclize contract was called. But there is not event that fired on callback called.

**Comment by nosuchip** [comment]
Just checked - it does not works even on Ropsten.

**Comment by nosuchip** [comment]
It even does not works in your own IDE: http://dapps.oraclize.it/browser-solidity/

**Comment by bertani** [comment]
Hello @nosuchip ,
on Rinkeby/Ropsten we had some delays in processing queries during the last few days - those are being addressed. However the callback [was correctly received]
(https://rinkeby.etherscan.io/tx/0x866e1da0e89b16dbdca442eb2bdcfeafbaf09338141de477c00f75578bcdb5d6) (late!) by the contract you mentioned in your first post.
[The browser-solidity IDE is known not to support the random datasource proof verification](https://github.com/oraclize/ethereum-examples/blob/master/solidity/random-datasource/README.md) as a real chain is needed to verify the commitment and the "vm mode" of browser-solidity is an "in-memory" execution.

I hope this helps!

**Comment by nosuchip** [comment]
@bertani thank you for the response. I still see that issues with Ropsten/Rinkeby persist. But I'd like to clarify one thing - if I understood right, I should be able to run that example with commented out line that checks proof in your dapp IDE. But it still failed on contract creation step with error `VM Exception: invalid opcode`

**Comment by marcogiglio** [comment]
Hi @nosuchip, the issue should now be resolved for the testnets. 
Regarding the VM Exception in our fork of the IDE: the connector which is deployed in the Javascript VM is not updated to implement the Random DS. For example, the function oraclize_randomDS_getSessionPubKeyHash is missing and it will cause a throw if its called from the contract.

**Comment by marcogiglio** [comment]
There was an issue with the testnet configuration: the context name was wrong, and it was causing the proof to fail. I have fixed it now. 
Regarding that other issue, the connector in the dapp IDE is not updated: it is missing the randomDS_getSessionPubKeyHash() function. When the example code calls that function, then it will throw and this is what happens in the constructor: constructor() -> update() -> oraclize_newRandomDSQuery -> oraclize_randomDS_getSessionPubKeyHash function -> randomDS_getSessionPubKeyHash().

**Comment by nosuchip** [comment]
It is fantastic, but today this call `oraclize_newRandomDSQuery(delay, randomBytesNumber, callbackGas);` fails all the day on `Rinkeby` network.

**Comment by bertani** [comment]
This is fixed now. The Oraclize free deployments on testnets are experimental and they can experience issues from time to time.
